### ISSUE TITLE
Global settings

### ISSUE THREAD

**Issue by VexTrex87** [VexTrex87/Gamer-Chill-Bot#39]
- Leveling Update Delay
- Leveling Level Difficulty
- Update Tickers Delay
- Ticker Period
- Ticker Interval
- Max Leaderboard Fields
- Max Fill
- Fill Emoji
- Unfill emoji
- Check emoji
- Next Emoji
- Back Emoji
- Change Emoji
- Max Memes
- Meme Subreddit
- Delete response delay
- Wait Delay

**Comment by Vex87** [comment]
Discontinued because it is not needed

**Comment by Vex87** [comment]
Not needed

**Comment by VexTrex87** [comment]
Not needed
